package MyPackages;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Astro
 */
public class DistributorsForm extends javax.swing.JFrame {

    /**
     * Creates new form DistributorsForm
     */
    Connection con;
    Statement stmt;
    PreparedStatement pstmt;
    
    public DistributorsForm() {
        initComponents();
        setSize(1389,718);
        
        show_user();
       
        this.setLocationRelativeTo(null);//center form in the screen
         
        try{
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/newspaperagency","root","");
        }
        catch(SQLException e){
              JOptionPane.showMessageDialog(null,e);
        
    }
      
        
        //To display data In table
        
       
    }
    
    
    public ArrayList<User> userList(){
        
        ArrayList<User> usersList = new ArrayList<>();
     
         
        try{
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/newspaperagency","root","");
            
            String q1="select * from distributor";
            
            stmt = (Statement) con.createStatement();   
            ResultSet rs= stmt.executeQuery(q1);
            User user;
            while(rs.next()){
                user=new User(rs.getInt("D_id"), rs.getString("Name"), rs.getString("Area"), rs.getInt("Contact"));
                usersList.add(user);
                
            }
           
        }
        catch(SQLException e){
              JOptionPane.showMessageDialog(null,e);
        
    }
      
        return usersList;
        
    }
    
    public void show_user(){
        
        ArrayList<User> list = userList();
        DefaultTableModel model = (DefaultTableModel) DistributorTable.getModel();
        
        Object[] row = new Object[4];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getD_id();
            row[1]=list.get(i).getName();
            row[2]=list.get(i).getArea();
            row[3]=list.get(i).getContact();
            
            model.addRow(row);
            
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Didfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Namefield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Contactfield = new javax.swing.JTextField();
        Addb = new javax.swing.JButton();
        Updateb = new javax.swing.JButton();
        Deleteb = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DistributorTable = new javax.swing.JTable();
        Exitb = new javax.swing.JButton();
        Clearb = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Areafield = new javax.swing.JComboBox<>();
        didv = new javax.swing.JLabel();
        namevv = new javax.swing.JLabel();
        cv = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(0, 0, 255));
        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel2.setText("      ABOUT DISTRIBUTORS");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 10, 319, 49);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setText("D_id :");

        Didfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DidfieldActionPerformed(evt);
            }
        });
        Didfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DidfieldKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setText("Name :");

        Namefield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NamefieldKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("Area :");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setText("Contact :");

        Contactfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ContactfieldKeyReleased(evt);
            }
        });

        Addb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Addb.setText("Add");
        Addb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbActionPerformed(evt);
            }
        });

        Updateb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Updateb.setText("Update");
        Updateb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebActionPerformed(evt);
            }
        });

        Deleteb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Deleteb.setText("Delete");
        Deleteb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebActionPerformed(evt);
            }
        });

        DistributorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "D_id", "Name", "Area", "Contact"
            }
        ));
        DistributorTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DistributorTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DistributorTable);

        Exitb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Exitb.setText("EXIT");
        Exitb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbActionPerformed(evt);
            }
        });

        Clearb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Clearb.setText("Clear");
        Clearb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearbActionPerformed(evt);
            }
        });

        Areafield.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Areafield.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chinchwad", "Akurdi", "Pimpri", "Chikali", "Rahatni" }));
        Areafield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreafieldActionPerformed(evt);
            }
        });

        didv.setForeground(new java.awt.Color(255, 0, 0));
        didv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                didvMouseReleased(evt);
            }
        });

        namevv.setForeground(new java.awt.Color(255, 51, 51));

        cv.setForeground(new java.awt.Color(255, 0, 0));
        cv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cvKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Addb, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(Updateb, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(Deleteb, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(Clearb, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                        .addComponent(Exitb, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(249, 249, 249))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Areafield, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Didfield, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Namefield)
                                    .addComponent(Contactfield, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(didv, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namevv, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addComponent(cv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(182, 182, 182))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Didfield, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(didv, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Namefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namevv, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Areafield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Contactfield)
                                        .addComponent(cv, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Deleteb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Clearb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Updateb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Addb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(145, 145, 145))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Exitb, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(84, 105, 1181, 508);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1400, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DidfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DidfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DidfieldActionPerformed

    private void AddbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbActionPerformed
       
        String D_id=Didfield.getText();
        String Dname=Namefield.getText();
        String Contact=Contactfield.getText();
        String Area=Areafield.getSelectedItem().toString();
      
        
        try{
            pstmt=con.prepareStatement("insert into distributor values(?,?,?,?)");
            pstmt.setString(1,D_id);
            pstmt.setString(2,Dname);
            pstmt.setString(3,Area);
            pstmt.setString(4,Contact);
            
            int i=pstmt.executeUpdate();
            
            DefaultTableModel model = (DefaultTableModel) DistributorTable.getModel();
              model.setRowCount(0);
              show_user();
        
            if(i>0){
                JOptionPane.showMessageDialog(null,"Distributor Added!!");
            }
            else{
                 JOptionPane.showMessageDialog(null,"Failed to add Distributor!");
                
                }
           }   
            
         catch (SQLException e) {
             JOptionPane.showMessageDialog(null,e);
         }
        
        
        
        
    }//GEN-LAST:event_AddbActionPerformed

    private void UpdatebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebActionPerformed
        // TODO add your handling code here:
        
         try{
        String Did=Didfield.getText();
        String Dname=Namefield.getText();
        String Area=Areafield.getSelectedItem().toString();
        String Contct=Contactfield.getText();

        
       // String ql = "update distributor set Name='"+Dname+"',Contact='"+Contct+"',Area='"+Area+"' where D_id='"+Did+"'";
            
            
            
            int row = DistributorTable.getSelectedRow();
            String value = (DistributorTable.getModel().getValueAt(row, 0).toString());
              String ql = "update distributor set Name=?,Area=?,Contact=? where D_id="+Did;
              pstmt=con.prepareStatement(ql);
              pstmt.setString(1, Namefield.getText());
              pstmt.setString(2, Areafield.getSelectedItem().toString());
              pstmt.setString(3, Contactfield.getText());
              
              pstmt.executeUpdate();
              
              //to display data in table always
              DefaultTableModel model = (DefaultTableModel) DistributorTable.getModel();
              model.setRowCount(0);
              show_user();
              
                          JOptionPane.showMessageDialog(null,"Updated!!!");

        }
        catch(Exception e){
                 
            JOptionPane.showMessageDialog(null,"Cannot Update data");
        }
    }//GEN-LAST:event_UpdatebActionPerformed

    private void DistributorTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DistributorTableMouseClicked
        // TODO add your handling code here:
        
        int i = DistributorTable.getSelectedRow();
        TableModel model =  DistributorTable.getModel();
        Didfield.setText(model.getValueAt(i,0).toString());
        Namefield.setText(model.getValueAt(i,1).toString());
        Areafield.setSelectedItem(model.getValueAt(i,2).toString());
        Contactfield.setText(model.getValueAt(i,3).toString());
    }//GEN-LAST:event_DistributorTableMouseClicked

    private void ClearbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearbActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_ClearbActionPerformed

    private void DeletebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebActionPerformed
        // TODO add your handling code here:
         String q1=" delete from distributor where D_id =? "; 
        try{
        
            pstmt=con.prepareStatement(q1);
            pstmt.setString(1,Didfield.getText());
            pstmt.execute();
            DefaultTableModel model = (DefaultTableModel) DistributorTable.getModel();
              model.setRowCount(0);
              show_user();
            
            JOptionPane.showMessageDialog(null,"Deleted Successfully!!!");
            
        }
        catch(Exception e){
                 
            JOptionPane.showMessageDialog(null,"Cant Delete!!!");
        }
        
    }//GEN-LAST:event_DeletebActionPerformed

    private void ExitbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbActionPerformed
        // TODO add your handling code here:
//        this.setVisible(false);
        new AdminPortal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExitbActionPerformed

    private void AreafieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreafieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AreafieldActionPerformed

    private void NamefieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NamefieldKeyReleased
        // TODO add your handling code here:
        
        
         String PATTERN;
        PATTERN = "^[a-zA-Z]+";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher( Namefield.getText());
        if(!match.matches()){
            namevv.setText("invalid");
               }
        else{
              namevv.setText(null);
            
        }
        
        
        
    }//GEN-LAST:event_NamefieldKeyReleased

    private void DidfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DidfieldKeyReleased
        // TODO add your handling code here:
        
        String PATTERN;
        PATTERN = "^[0-9]+$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(Didfield.getText());
        if(!match.matches()){
            didv.setText("Invalid");
               }
        else{
            
              didv.setText(null);
            
        }
        
        
        
    }//GEN-LAST:event_DidfieldKeyReleased

    private void ContactfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContactfieldKeyReleased
        // TODO add your handling code here:
        
           
        
        String PATTERN;
        PATTERN = "^[0-9]{9}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher( Contactfield.getText());
        if(!match.matches()){
            cv.setText("Invalid!!!");
               }
        else{
              cv.setText(null);
            
        }
        
        
        
        
    }//GEN-LAST:event_ContactfieldKeyReleased

    private void cvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cvKeyReleased
        
    }//GEN-LAST:event_cvKeyReleased

    private void didvMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_didvMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_didvMouseReleased

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DistributorsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DistributorsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DistributorsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DistributorsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DistributorsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addb;
    private javax.swing.JComboBox<String> Areafield;
    private javax.swing.JButton Clearb;
    private javax.swing.JTextField Contactfield;
    private javax.swing.JButton Deleteb;
    private javax.swing.JTextField Didfield;
    private javax.swing.JTable DistributorTable;
    private javax.swing.JButton Exitb;
    private javax.swing.JTextField Namefield;
    private javax.swing.JButton Updateb;
    private javax.swing.JLabel cv;
    private javax.swing.JLabel didv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel namevv;
    // End of variables declaration//GEN-END:variables


void clear(){
        
            Didfield.setText("");
            Namefield.setText("");
            Areafield.setSelectedItem("");
            Contactfield.setText("");
                   
        }

    private void executeQuery(String q1, String deleted) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
  
}

