package MyPackages;

//import java.beans.Statement;
import static com.sun.webkit.perf.WCFontPerfLogger.reset;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.util.regex.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Astro
 */
public class UserForm extends javax.swing.JFrame {

    /**
     * Creates new form UserForm
     */
    
    
    Connection con;
    Statement stmt;
    PreparedStatement pstmt;
    
    public UserForm() {
       
        initComponents();
        setSize(1389,718);
              
       
         this.setLocationRelativeTo(null);//center form in the screen
         
        try{
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/newspaperagency","root","");
        }
        catch(SQLException e){
              JOptionPane.showMessageDialog(null,e);
        
    }
        
}
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Addrssarea = new javax.swing.JTextArea();
        fnameField = new javax.swing.JTextField();
        lastField = new javax.swing.JTextField();
        Emailfield = new javax.swing.JTextField();
        contctfield = new javax.swing.JTextField();
        CreateButton = new javax.swing.JButton();
        Cancelb = new javax.swing.JButton();
        Areacombo = new javax.swing.JComboBox<>();
        DOBfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Cidfield = new javax.swing.JTextField();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        Clearb = new javax.swing.JButton();
        Searchb = new javax.swing.JButton();
        viewbutton = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        pn = new javax.swing.JLabel();
        papername = new javax.swing.JComboBox<>();
        namelabel = new javax.swing.JLabel();
        lastnamelabel = new javax.swing.JLabel();
        emaillael = new javax.swing.JLabel();
        emailv = new javax.swing.JLabel();
        contactv = new javax.swing.JLabel();
        dobv = new javax.swing.JLabel();
        cidv = new javax.swing.JLabel();
        dobb = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel1.setText("Customer Details");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Firstname");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Lastname");

        jLabel4.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jLabel4.setText("Email");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Contact Details");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Date Of Birth(DOB)");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Addresss");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Area ");

        Addrssarea.setColumns(20);
        Addrssarea.setRows(5);
        jScrollPane1.setViewportView(Addrssarea);

        fnameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fnameFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fnameFieldKeyTyped(evt);
            }
        });

        lastField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lastFieldKeyReleased(evt);
            }
        });

        Emailfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailfieldActionPerformed(evt);
            }
        });
        Emailfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EmailfieldKeyReleased(evt);
            }
        });

        contctfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                contctfieldKeyReleased(evt);
            }
        });

        CreateButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CreateButton.setText("Add");
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });

        Cancelb.setText("Cancel");
        Cancelb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelbActionPerformed(evt);
            }
        });

        Areacombo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Areacombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chinchwad", "Akurdi", "Pimpri", "Chikali", "Rahatni" }));
        Areacombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreacomboActionPerformed(evt);
            }
        });

        DOBfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DOBfieldKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel5.setText("C_id :");

        Cidfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CidfieldKeyReleased(evt);
            }
        });

        UpdateButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        DeleteButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        Clearb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Clearb.setText("Clear");
        Clearb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearbActionPerformed(evt);
            }
        });

        Searchb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Searchb.setText("Search");
        Searchb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchbActionPerformed(evt);
            }
        });

        viewbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewbutton.setText("View Customer");
        viewbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbuttonActionPerformed(evt);
            }
        });

        Back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        pn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pn.setText("Papername");

        papername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        papername.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Lokmat", "Times Of India", "Jaagaran Samachar" }));
        papername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                papernameActionPerformed(evt);
            }
        });

        namelabel.setForeground(new java.awt.Color(255, 0, 0));

        lastnamelabel.setForeground(new java.awt.Color(255, 0, 0));

        emaillael.setForeground(new java.awt.Color(255, 0, 51));

        emailv.setForeground(new java.awt.Color(255, 0, 0));

        contactv.setForeground(new java.awt.Color(255, 0, 0));

        dobv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dobv.setText("YYYY/MM/DD");

        cidv.setForeground(new java.awt.Color(255, 0, 0));

        dobb.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(CreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(pn)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(75, 75, 75)
                                                .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(papername, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(DOBfield, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(Areacombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18, 18, 18)
                                                        .addComponent(dobb, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGap(45, 45, 45)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(viewbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Emailfield, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                            .addComponent(contctfield, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                            .addComponent(lastField, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                            .addComponent(fnameField)
                                            .addComponent(Cidfield, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(emailv, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(emaillael, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(cidv, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(contactv, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(Searchb, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(lastnamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(53, 53, 53)
                                                            .addComponent(Clearb, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(406, 406, 406)
                        .addComponent(Cancelb, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(dobv, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(cidv, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cidfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastnamelabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Clearb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emaillael, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(emailv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Emailfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contactv, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Searchb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(contctfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DOBfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dobb, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(dobv, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Areacombo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(Cancelb, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pn)
                                    .addComponent(papername, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(250, 40, 725, 650);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1400, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
 
      
        
        String C_id=Cidfield.getText();
        String Fname=fnameField.getText();
        String Lname=lastField.getText();
        String Email=Emailfield.getText();
        String Contact=contctfield.getText();
        String dateBirth=DOBfield.getText();
        //int index=Areacombo.getSelectedIndex();
        String Area=Areacombo.getSelectedItem().toString();
        String Address=Addrssarea.getText();
        String Papername=papername.getSelectedItem().toString();
        
        if(C_id.equals("")){
            JOptionPane.showMessageDialog(null,"C_id is Mandatory!!");
        }
         if(Fname.equals("")){
            JOptionPane.showMessageDialog(null,"Firstname Required!!");
        }
         if(Lname.equals("")){
            JOptionPane.showMessageDialog(null,"Lastname Required!!");
        }
         if(Email.equals("")){
            JOptionPane.showMessageDialog(null,"Email-id Required!!");
        }
         if(Contact.equals("")){
            JOptionPane.showMessageDialog(null,"Contact is Mandatory!!");
         }
        
         if(dateBirth.equals("")){
            JOptionPane.showMessageDialog(null,"DOB Required!!");
        }
         if(Area.equals("")){
            JOptionPane.showMessageDialog(null,"please select Area!!");
        }
         if(Address.equals("")){
            JOptionPane.showMessageDialog(null," Address is Mandatory!!");
        }
        
         
        
        try{
            pstmt=con.prepareStatement("insert into customer values(?,?,?,?,?,?,?,?,?)");
            pstmt.setString(1,C_id);
            pstmt.setString(2,Fname);
            pstmt.setString(3,Lname);
            pstmt.setString(4,Email);
            pstmt.setString(5,Contact);
            pstmt.setString(6,dateBirth);
            pstmt.setString(7,Area);
            pstmt.setString(8,Address);
                    pstmt.setString(9,Papername);
            int i=pstmt.executeUpdate();
            
            if(i>0){
                JOptionPane.showMessageDialog(null,"Customer Added Successfully!!");
            }
            else{
                 JOptionPane.showMessageDialog(null,"Failed to add Customer!");
                
                }
           }   
            
         catch (SQLException ex) {
            Logger.getLogger(UserForm.class.getName()).log(Level.SEVERE, null, ex);
                     JOptionPane.showMessageDialog(null,ex);
                    
        }
        
  
    }//GEN-LAST:event_CreateButtonActionPerformed

    private void CancelbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelbActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
         new AdminPortal().setVisible(true);
    }//GEN-LAST:event_CancelbActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
       
        int opt = JOptionPane.showConfirmDialog(null,"Are you sure to delete??","Delete",JOptionPane.YES_NO_OPTION);
        if(opt==0){
        String sql=" delete from customer where C_id =? "; 
        try{
        
            pstmt=con.prepareStatement(sql);
            pstmt.setString(1,Cidfield.getText());
            pstmt.execute();
            JOptionPane.showMessageDialog(null,"Customer Removed");
            
        }
        catch(Exception e){
                 
            JOptionPane.showMessageDialog(null,"Cant Delete");
        }
        }
        
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void ClearbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearbActionPerformed
        // TODO add your handling code here:
        reset();
       
    }//GEN-LAST:event_ClearbActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        try{
        String C_id=Cidfield.getText();
        String Fname=fnameField.getText();
        String Lname=lastField.getText();
        String Email=Emailfield.getText();
        String Contact=contctfield.getText();
        String dateBirth=DOBfield.getText();
        //int index=Areacombo.getSelectedIndex();
        String Area=Areacombo.getSelectedItem().toString();
        String Address=Addrssarea.getText();
      
        
        String sql = "update customer set Firstname='"+Fname+"',Lastname='"+Lname+"',Email='"+Email+"',Contact='"+Contact+"',dateBirth='"+dateBirth+"',Area='"+Area+"',Address='"+Address+"' where C_id='"+C_id+"'";
            pstmt=con.prepareStatement(sql);
            pstmt.execute();
            JOptionPane.showMessageDialog(null,"Customer Updated!!!");
            
        }
        catch(Exception e){
                 
            JOptionPane.showMessageDialog(null,"Customer CANNOT Be Updated!!!!");
        }
       
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void SearchbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchbActionPerformed
        
         String sql=" select * from customer where C_id =? "; 
        try{
            
            pstmt=con.prepareStatement(sql);
            pstmt.setString(1,Cidfield.getText());
          
            
             ResultSet rs = pstmt.executeQuery();
           if(rs.next()){
              // String add1 = rs.getString("C_id");
               //Cidfield.setText(add1);
               String add2 = rs.getString("Firstname");
               fnameField.setText(add2);
               String add3 = rs.getString("Lastname");
               lastField.setText(add3);
               String add4 = rs.getString("Email");
               Emailfield.setText(add4);
               String add5 = rs.getString("Contact");
               contctfield.setText(add5);
               String add6 = rs.getString("dateBirth");
               DOBfield.setText(add6);
               String add7 = rs.getString("Area");
               Areacombo.setSelectedItem(add7);
               String add8 = rs.getString("Address");
               Addrssarea.setText(add8);
              String add9 = rs.getString("papername");
              papername.setSelectedItem(add9);
              
               JOptionPane.showMessageDialog(null,"Record Found!!");
           }
           else{  
            JOptionPane.showMessageDialog(null,"Record NOT Found!!");
           }
        }
        catch(Exception e){
                 
            JOptionPane.showMessageDialog(null,e);
        }
        
     
    }//GEN-LAST:event_SearchbActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here
        this.setVisible(false);
        new AdminPortal().setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void viewbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbuttonActionPerformed
       
        customerTable Info=new customerTable();
        Info.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_viewbuttonActionPerformed

    private void papernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_papernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_papernameActionPerformed

    private void fnameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameFieldKeyReleased
        // TODO add your handling code here:
     
        String PATTERN;
        PATTERN = "^[a-zA-Z]+";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(fnameField.getText());
        if(!match.matches()){
            namelabel.setText("invalid");
               }
        else{
              namelabel.setText(null);
            
        }
        
       
        
        
    }//GEN-LAST:event_fnameFieldKeyReleased

    private void fnameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameFieldKeyTyped
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_fnameFieldKeyTyped

    private void lastFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastFieldKeyReleased
        // TODO add your handling code here:
         String PATTERN;
        PATTERN = "^[a-zA-Z]+";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(lastField.getText());
        if(!match.matches()){
            lastnamelabel.setText("Invalid");
               }
        else{
              lastnamelabel.setText(null);
            
        }
        
       
        
        
    }//GEN-LAST:event_lastFieldKeyReleased

    private void EmailfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailfieldKeyReleased
        // TODO add your handling code here:
         String PATTERN;
        PATTERN = "^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(Emailfield.getText());
        if(!match.matches()){
            emailv.setText("Invalid!!!");
               }
        else{
              emailv.setText(null);
            
        }
        
       
        
    }//GEN-LAST:event_EmailfieldKeyReleased

    private void EmailfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailfieldActionPerformed

    private void CidfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CidfieldKeyReleased

String PATTERN;
        PATTERN = "^[0-9]+$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(Cidfield.getText());
        if(!match.matches()){
            cidv.setText("Invalid!!!");
               }
        else{
              cidv.setText(null);
            
        }
        





        // TODO add your handling code here:
    }//GEN-LAST:event_CidfieldKeyReleased

    private void contctfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contctfieldKeyReleased
        // TODO add your handling code here:
        
        String PATTERN;
        PATTERN = "^[0-9]{10}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(contctfield.getText());
        if(!match.matches()){
            contactv.setText("Invalid!!!");
               }
        else{
              contactv.setText(null);
            
        }
        
    }//GEN-LAST:event_contctfieldKeyReleased

    private void AreacomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreacomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AreacomboActionPerformed

    private void DOBfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DOBfieldKeyReleased
        // TODO add your handling code here:
        
        
        
           
        
      
        
    }//GEN-LAST:event_DOBfieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Addrssarea;
    private javax.swing.JComboBox<String> Areacombo;
    private javax.swing.JButton Back;
    private javax.swing.JButton Cancelb;
    private javax.swing.JTextField Cidfield;
    private javax.swing.JButton Clearb;
    private javax.swing.JButton CreateButton;
    private javax.swing.JTextField DOBfield;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JTextField Emailfield;
    private javax.swing.JButton Searchb;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel cidv;
    private javax.swing.JLabel contactv;
    private javax.swing.JTextField contctfield;
    private javax.swing.JLabel dobb;
    private javax.swing.JLabel dobv;
    private javax.swing.JLabel emaillael;
    private javax.swing.JLabel emailv;
    private javax.swing.JTextField fnameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastField;
    private javax.swing.JLabel lastnamelabel;
    private javax.swing.JLabel namelabel;
    private javax.swing.JComboBox<String> papername;
    private javax.swing.JLabel pn;
    private javax.swing.JButton viewbutton;
    // End of variables declaration//GEN-END:variables

   /* private void execute() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
*/

  void reset(){
        
            Cidfield.setText("");
            fnameField.setText("");
            lastField.setText("");
            Emailfield.setText("");
            contctfield.setText("");
            DOBfield.setText("");
            Addrssarea.setText("");
            Areacombo.setSelectedItem("");
                   
        }

 



    private boolean Contact_validation() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}

